version: "1.0"
services:
  www:
    build: .
    restart: always
    container_name: www
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/html
    networks:
      - default
  db:
    image: mysql:5.6
    container_name: mysql56
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - default

volumes:
  db_data:
